import type { DBSPlan, FormattedInvoice, TicketRecord } from '../../types';

// Catalog used only by an explicitly opted-in development demo.
export const MOCK_PLANS: DBSPlan[] = [
  {
    id: 'dbs-400',
    name: 'Seja DBS 400MB',
    speed: '400 Mega',
    downloadMbps: 400,
    uploadMbps: 200,
    price: 109.9,
    type: 'URBANO',
    description: 'Ideal para navegação diária, redes sociais e streaming em HD.',
    recommendedForDevices: 'Até 4 dispositivos',
    features: [
      'Download 400 Mbps / Upload 200 Mbps',
      'Instalação 100% gratuita no plano fidelidade',
      'Wi-Fi Dual Band incluso',
      'Valor fixo mensal',
    ],
  },
  {
    id: 'dbs-500',
    name: 'Ideal DBS 500MB',
    speed: '500 Mega',
    downloadMbps: 500,
    uploadMbps: 250,
    price: 139.9,
    priceOnTime: 119.9,
    type: 'URBANO',
    isPopular: true,
    description: 'Nosso plano mais vendido! Perfeito para famílias conectadas e home office.',
    recommendedForDevices: 'De 4 a 8 dispositivos',
    features: [
      'Download 500 Mbps / Upload 250 Mbps',
      'Super desconto até o vencimento: R$ 119,90',
      'Instalação gratuita com fidelidade 12 meses',
      'Roteador Dual Band alta performance',
    ],
  },
  {
    id: 'dbs-600',
    name: 'Essencial DBS 600MB',
    speed: '600 Mega',
    downloadMbps: 600,
    uploadMbps: 300,
    price: 149.9,
    priceOnTime: 139.9,
    type: 'URBANO',
    description: 'Alta velocidade para streaming em 4K e múltiplos acessos simultâneos.',
    recommendedForDevices: '6 a 10 dispositivos',
    features: [
      'Download 600 Mbps / Upload 300 Mbps',
      'Desconto de pontualidade: R$ 139,90',
      'Instalação gratuita com fidelidade',
      'Prioridade na fila de atendimento',
    ],
  },
  {
    id: 'dbs-800',
    name: 'Entretenimento DBS 800MB',
    speed: '800 Mega',
    downloadMbps: 800,
    uploadMbps: 400,
    price: 159.9,
    type: 'URBANO',
    description: 'Ultra velocidade para gamers, downloads pesados e casas inteligentes.',
    recommendedForDevices: '8 a 15 dispositivos',
    features: [
      'Download 800 Mbps / Upload 400 Mbps',
      'Valor fixo sem surpresas',
      'Baixíssima latência para jogos online',
      'Equipamento Gigabit incluso',
    ],
  },
  {
    id: 'dbs-1gb',
    name: 'Hard DBS 1GB',
    speed: '1 Giga (1000 Mega)',
    downloadMbps: 1000,
    uploadMbps: 500,
    price: 249.9,
    type: 'URBANO',
    description: 'A potência máxima da fibra ótica DBS Telecom.',
    recommendedForDevices: '15+ dispositivos',
    features: [
      'Download 1000 Mbps / Upload 500 Mbps',
      'Equipamento topo de linha Wi-Fi 6',
      'Suporte VIP prioritário',
      'Valor fixo mensal',
    ],
  },
  {
    id: 'dbs-retencao-300',
    name: 'Retenção DBS 300MB',
    speed: '300 Mega',
    downloadMbps: 300,
    uploadMbps: 150,
    price: 89.9,
    type: 'RETENCAO',
    description: 'Plano especial econômico para retenção e necessidades especiais.',
    recommendedForDevices: 'Até 3 dispositivos',
    features: [
      'Download 300 Mbps / Upload 150 Mbps',
      'Fibra ótica com estabilidade garantida',
      'Valor fixo mensal de R$ 89,90',
    ],
  },
  {
    id: 'wifi6-500',
    name: 'DBS Wi-Fi 6 500MB',
    speed: '500 Mega Wi-Fi 6',
    downloadMbps: 500,
    uploadMbps: 250,
    price: 119.9,
    type: 'WIFI6',
    description: 'Tecnologia 802.11ax: mais estabilidade e alcance sem interferências.',
    recommendedForDevices: 'Muitos aparelhos conectados',
    features: [
      'Roteador Wi-Fi 6 de última geração (802.11ax)',
      'Menor congestionamento e mais alcance',
      'Ponto adicional por apenas +R$ 19,90/mês',
    ],
  },
  {
    id: 'wifi6-600',
    name: 'DBS Wi-Fi 6 600MB',
    speed: '600 Mega Wi-Fi 6',
    downloadMbps: 600,
    uploadMbps: 300,
    price: 129.9,
    type: 'WIFI6',
    description: 'Combinação imbatível de velocidade e estabilidade com Wi-Fi 6.',
    recommendedForDevices: 'Casas com múltiplos usuários e IoT',
    features: [
      'Roteador Wi-Fi 6 incluso',
      'Suporte a múltiplos streamings simultâneos',
      'Ponto adicional por apenas +R$ 19,90/mês',
    ],
  },
  {
    id: 'wifi6-800',
    name: 'DBS Wi-Fi 6 800MB',
    speed: '800 Mega Wi-Fi 6',
    downloadMbps: 800,
    uploadMbps: 400,
    price: 159.9,
    type: 'WIFI6',
    isPopular: true,
    description: 'Plano Premium com tecnologia Wi-Fi 6 (802.11ax) para ultra estabilidade.',
    recommendedForDevices: '8+ aparelhos e gamers',
    features: [
      'Tecnologia Wi-Fi 6 avançada (802.11ax)',
      'Ideal para muitas pessoas e aparelhos simultâneos',
      'Ponto adicional por apenas +R$ 19,90/mês',
    ],
  },
  {
    id: 'wifi6-1000',
    name: 'DBS Wi-Fi 6 1000MB',
    speed: '1000 Mega Wi-Fi 6',
    downloadMbps: 1000,
    uploadMbps: 500,
    price: 189.9,
    type: 'WIFI6',
    description: 'Velocidade extrema e cobertura Wi-Fi 6 para toda a casa.',
    recommendedForDevices: 'Famílias grandes, gamers e criadores de conteúdo',
    features: [
      'Roteador Wi-Fi 6 topo de linha',
      'Máxima capacidade de conexão simultânea',
      'Ponto adicional por apenas +R$ 19,90/mês',
    ],
  },
];

// Legacy demo fixtures. These are unreachable unless demo mode is explicitly
// enabled and are never used as live customer or financial responses.
export const MOCK_INVOICES: FormattedInvoice[] = [
  {
    id: '145690',
    documento: '71820',
    valor: 119.9,
    valorFormatado: 'R$ 119,90',
    dataEmissao: '2026-08-10',
    dataVencimento: '2026-09-10',
    dataVencimentoFormatada: '10/09/2026',
    status: 'PENDENTE',
    linhaDigitavel: '04790000020000014569803047711654260000011990',
    linhaDigitavelFormatada: '04790.00002 00000.145698 03047.711654 2 60000011990',
    pixCopiaECola: '00020126580014br.gov.bcb.pix0136dbstelecom-145690-pix@dbstelecom.com.br5204000053039865406119.905802BR5911DBS TELECOM6007CHAPECO62070503***6304',
    obs: 'Plano DBS Fibra 500MB (Com desconto pontualidade)',
    isOverdue: false,
  },
];

// Legacy demo fixtures. These are unreachable unless demo mode is explicitly
// enabled and are never used as live customer or support responses.
export const MOCK_TICKETS: TicketRecord[] = [
  {
    id: '8472',
    id_cliente: '2270',
    id_contrato: '2323',
    tipo: 'C',
    assunto: 'Instalação e Troca de Roteador Wi-Fi 6',
    mensagem: 'Cliente solicitou upgrade para Wi-Fi 6 e troca programada de equipamento.',
    status: 'EC',
    statusLabel: 'Técnico a Caminho',
    prioridade: 'A',
    protocolo: 'DBS-781920',
    data_abertura: '2026-08-18 14:30:00',
    nome_tecnico: 'Carlos Eduardo (Equipe DBS Campo 04)',
    previsao_visita: 'Hoje até às 17:30',
    etapas: [
      { titulo: 'Chamado Aberto', descricao: 'Solicitação registrada no sistema IXC.', concluido: true, dataHora: '18/08 às 14:30' },
      { titulo: 'Triagem & Análise', descricao: 'Equipe de Nível 2 confirmou agendamento.', concluido: true, dataHora: '18/08 às 15:00' },
      { titulo: 'Técnico a Caminho', descricao: 'Técnico Carlos Eduardo em deslocamento com equipamento Wi-Fi 6.', concluido: true, dataHora: '19/08 às 10:15' },
      { titulo: 'Conclusão da Visita', descricao: 'Testes de velocidade e assinatura da O.S.', concluido: false },
    ],
  },
  {
    id: '7921',
    id_cliente: '2270',
    id_contrato: '2323',
    tipo: 'C',
    assunto: 'Verificação de Atenuação de Fibra Ótica',
    mensagem: 'Manutenção preventiva e aferição de potência de sinal ótico (-19.2 dBm OK).',
    status: 'C',
    statusLabel: 'Concluído',
    prioridade: 'M',
    protocolo: 'DBS-654120',
    data_abertura: '2026-07-22 09:15:00',
    data_fechamento: '2026-07-22 11:40:00',
    nome_tecnico: 'Rodrigo Antunes',
    etapas: [
      { titulo: 'Chamado Aberto', descricao: 'Abertura via WhatsApp/App DBS.', concluido: true, dataHora: '22/07 às 09:15' },
      { titulo: 'Análise de Link', descricao: 'Verificação remota da porta PON.', concluido: true, dataHora: '22/07 às 09:40' },
      { titulo: 'Visita Técnica', descricao: 'Limpeza de conector e teste de potência.', concluido: true, dataHora: '22/07 às 11:20' },
      { titulo: 'Finalizado', descricao: 'Sinal 100% estabilizado.', concluido: true, dataHora: '22/07 às 11:40' },
    ],
  },
];

