import { StyleSheet } from 'react-native';
import { RADIUS, SHADOWS } from '../../constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    padding: 16,
    paddingBottom: 36,
  },
  heroCard: {
    borderRadius: RADIUS.lg,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    marginBottom: 14,
    ...SHADOWS.md,
  },
  avatarCircle: {
    width: 64,
    height: 64,
    borderRadius: RADIUS.full,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    ...SHADOWS.primary,
  },
  avatarText: {
    fontSize: 26,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  userName: {
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  userDoc: {
    fontSize: 12,
    marginTop: 2,
    fontWeight: '500',
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    marginTop: 10,
  },
  statusText: {
    fontSize: 11,
    fontWeight: '800',
  },
  sectionCard: {
    borderRadius: RADIUS.lg,
    padding: 16,
    borderWidth: 1,
    marginBottom: 12,
    ...SHADOWS.sm,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    paddingBottom: 10,
    marginBottom: 12,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionTitle: {
    fontSize: 13.5,
    fontWeight: '800',
  },
  themeSelectorRow: {
    flexDirection: 'row',
    gap: 8,
  },
  themeOptionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: RADIUS.md,
    borderWidth: 1,
  },
  themeOptionBtnActive: {
    borderWidth: 1.5,
  },
  themeOptionText: {
    fontSize: 12,
    fontWeight: '600',
  },
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: RADIUS.full,
  },
  liveDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
  },
  liveText: {
    fontSize: 10,
    fontWeight: '800',
  },
  networkInfoGrid: {
    flexDirection: 'row',
    padding: 10,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
  },
  networkItem: {
    flex: 1,
  },
  networkLabel: {
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  networkValue: {
    fontSize: 12.5,
    fontWeight: '800',
    marginTop: 2,
  },
  pingResultBox: {
    borderWidth: 1,
    borderRadius: RADIUS.sm,
    padding: 10,
    marginTop: 10,
  },
  pingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  pingCol: {},
  pingLabel: {
    fontSize: 9.5,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  pingValHighlight: {
    fontSize: 14,
    fontWeight: '900',
    marginTop: 1,
  },
  pingStatusText: {
    fontSize: 11,
    fontWeight: '700',
    marginTop: 4,
  },
  diagBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderWidth: 1,
    paddingVertical: 10,
    borderRadius: RADIUS.sm,
    marginTop: 10,
  },
  diagBtnText: {
    fontSize: 12,
    fontWeight: '700',
  },
  shortcutRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 9,
    borderBottomWidth: 1,
    gap: 12,
  },
  shortcutIconBox: {
    width: 34,
    height: 34,
    borderRadius: RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shortcutContent: {
    flex: 1,
  },
  shortcutTitle: {
    fontSize: 13,
    fontWeight: '800',
  },
  shortcutDesc: {
    fontSize: 11,
    marginTop: 1,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
    paddingVertical: 4,
  },
  infoIconBox: {
    width: 28,
    height: 28,
    borderRadius: RADIUS.xs,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoContent: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 10.5,
    fontWeight: '600',
  },
  infoValue: {
    fontSize: 12.5,
    fontWeight: '700',
    marginTop: 1,
  },
  channelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 4,
  },
  channelIconBox: {
    width: 34,
    height: 34,
    borderRadius: RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  channelContent: {
    flex: 1,
  },
  channelTitle: {
    fontSize: 13,
    fontWeight: '800',
  },
  channelDesc: {
    fontSize: 11,
    marginTop: 1,
  },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1.5,
    paddingVertical: 13,
    borderRadius: RADIUS.md,
    marginTop: 4,
  },
  logoutBtnText: {
    fontWeight: '800',
    fontSize: 13.5,
  },
  biometricRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    marginBottom: 4,
  },
  biometricRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  biometricLabel: {
    fontSize: 13.5,
    fontWeight: '800',
  },
  biometricSubLabel: {
    fontSize: 11,
    marginTop: 1,
  },
  securityInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: RADIUS.sm,
    marginTop: 8,
  },
  securityInfoText: {
    fontSize: 11.5,
    fontWeight: '600',
    flex: 1,
  },
  speedTestEntry: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    marginBottom: 12,
    gap: 14,
    ...SHADOWS.sm,
  },
  speedTestIcon: {
    width: 46,
    height: 46,
    borderRadius: RADIUS.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  speedTestTitle: {
    fontSize: 14,
    fontWeight: '900',
  },
  speedTestDesc: {
    fontSize: 11.5,
    marginTop: 2,
  },
});
